name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x
    - name: Restore dependencies
      run: dotnet restore $GITHUB_WORKSPACE/src/MyDemoApp/MyDemoApp.sln
    - name: Build
      run: dotnet build $GITHUB_WORKSPACE/src/MyDemoApp/MyDemoApp.sln --no-restore
    - name: Test
      run: dotnet test $GITHUB_WORKSPACE/src/MyDemoApp/MyDemoApp.sln --no-build --verbosity normal
    - name: Run Coverlet for Coverage
      uses: b3b00/coverlet-action@1.1.0
      with:
        testProject: '$GITHUB_WORKSPACE/src/MyDemoApp/MyDemoApp.Tests/MyDemoApp.Tests.csproj'
        output: 'lcov.info'
        outputFormat: 'lcov'
        excludes: '[program]*,[test]test.*'
